
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: ecommerce
    password: ecommerce
    tomcat.max-wait: 20000
    tomcat.max-active: 50
    tomcat.max-idle: 20
    tomcat.min-idle: 15
    validationQuery: SELECT 1
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  #Spring boot JPA insert in TABLE with uppercase name with Hibernate
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


management:
  server:
    port: ${PORT:8091}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
eureka:
  client:
    serviceUrl: 
      defaultZone:  http://localhost:8761/eureka/
