spring:
  datasource:
    jdbc-url: jdbc:h2:mem:db;MODE=MYSQL;INIT=CREATE SCHEMA IF NOT EXISTS `ecommerce`\; SET SCHEMA `ecommerce`\;
    username: sa
    password: sa
    maximum-pool-size: 2
    pool-size: 2 
  jpa:
    properties:
      hibernate:
        format_sql: true
flyway:
  enabled: false

logging:
    org:
      hibernate:
        SQL: DEBUG
